int add(int a1, int a2);
int mul(int a1, int a2);
int add4(int a1, int a2, int a3, int a4);
void push(int a);
int pop(void);
void sadd(void);
void smul(void);
void funcCall(int func(), int args);
char *copystr(const char *src);
void printLnInt(int v);
